global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'backend-apis'
    static_configs:
      - targets: 
        - 'host.docker.internal:3001'  # 2fa-api
        - 'host.docker.internal:3005'  # jwt-auth-api
        - 'host.docker.internal:3022'  # weather-api
        - 'host.docker.internal:3023'  # quotes-api
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elk-stack'
    static_configs:
      - targets:
        - 'host.docker.internal:9200'  # elasticsearch
        - 'host.docker.internal:5601'  # kibana
    scrape_interval: 60s