apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-api
  namespace: backend-projects
  labels:
    app: fitness-tracker-api
    category: crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-tracker-api
  template:
    metadata:
      labels:
        app: fitness-tracker-api
        category: crud
    spec:
      containers:
      - name: fitness-tracker-api
        image: fitness-tracker-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-api-service
  namespace: backend-projects
  labels:
    app: fitness-tracker-api
spec:
  selector:
    app: fitness-tracker-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP