name: Health Check

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'
      
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_PROD }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
      
      - name: Check service health
        run: |
          export KUBECONFIG=kubeconfig
          
          # Check all deployments
          kubectl get deployments -n backend-projects -o json | jq -r '.items[] | select(.status.readyReplicas != .status.replicas) | .metadata.name' > unhealthy.txt
          
          if [ -s unhealthy.txt ]; then
            echo "Unhealthy services found:"
            cat unhealthy.txt
            
            # Restart unhealthy services
            while read service; do
              echo "Restarting $service"
              kubectl rollout restart deployment/$service -n backend-projects
            done < unhealthy.txt
            
            exit 1
          else
            echo "All services are healthy"
          fi
      
      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: 'Health check failed - some services are unhealthy'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}